export type RoleCode = "super_admin" | "system_admin" | "dean" | "dept_admin" | "user" | "viewer";

export type PermissionCode =
  | "DASHBOARD_VIEW" | "DASHBOARD_MANAGE"
  | "APPLICATION_HUB_VIEW" | "APPLICATION_HUB_MANAGE" | "APPLICATION_HUB_PIN"
  | "INTRANET_VIEW" | "INTRANET_CREATE" | "INTRANET_EDIT" | "INTRANET_DELETE" | "INTRANET_PUBLISH"
  | "BOOK_MEETING_VIEW" | "BOOK_MEETING_CREATE" | "BOOK_MEETING_EDIT" | "BOOK_MEETING_DELETE" | "BOOK_MEETING_APPROVE"
  | "DOCUMENTS_VIEW" | "DOCUMENTS_UPLOAD" | "DOCUMENTS_EDIT" | "DOCUMENTS_DELETE" | "DOCUMENTS_SHARE" | "DOCUMENTS_MANAGE_POOL"
  | "PROJECTS_VIEW" | "PROJECTS_CREATE" | "PROJECTS_EDIT" | "PROJECTS_DELETE" | "PROJECTS_APPROVE" | "PROJECTS_MANAGE_ALL"
  | "USERS_VIEW" | "USERS_CREATE" | "USERS_EDIT" | "USERS_DELETE" | "USERS_MANAGE_ROLES" | "USERS_MANAGE_PERMISSIONS" | "USERS_AD_SYNC" | "USERS_BULK_IMPORT"
  | "USERS_BULK_ASSIGN_ROLE" | "USERS_BULK_ENABLE" | "USERS_BULK_DISABLE" | "USERS_UNLOCK_ACCOUNT" | "USERS_RESET_MFA" | "USERS_EXPORT_SELECTED"
  | "AUDIT_LOG_VIEW" | "AUDIT_LOG_EXPORT" | "AUDIT_LOG_MANAGE"
  | "SETTINGS_VIEW" | "SETTINGS_MANAGE" | "SETTINGS_API_KEYS" | "SETTINGS_BRANDING" | "SETTINGS_NOTIFICATION" | "SETTINGS_SSO"
  | "ERP_VIEW" | "ERP_MANAGE" | "ERP_APPROVE" | "ERP_REPORT"
  | "E_OFFICE_VIEW" | "E_OFFICE_CREATE" | "E_OFFICE_APPROVE" | "E_OFFICE_MANAGE"
  | "DOCUMENT_MANAGEMENT_VIEW" | "DOCUMENT_MANAGEMENT_UPLOAD" | "DOCUMENT_MANAGEMENT_MANAGE" | "DOCUMENT_MANAGEMENT_OCR"
  | "ACADEMIC_VIEW" | "ACADEMIC_MANAGE" | "ACADEMIC_EXAM"
  | "HR_VIEW" | "HR_MANAGE" | "HR_PAYROLL" | "HR_ATTENDANCE"
;

export const ROLE_LEVELS: Record<RoleCode, number> = {
  super_admin: 100,
  system_admin: 80,
  dean: 70,
  dept_admin: 50,
  user: 30,
  viewer: 10,
};

export const ROLE_PERMISSIONS: Record<RoleCode, PermissionCode[]> = {
  super_admin: [
    "DASHBOARD_VIEW", "DASHBOARD_MANAGE",
    "APPLICATION_HUB_VIEW", "APPLICATION_HUB_MANAGE", "APPLICATION_HUB_PIN",
    "INTRANET_VIEW", "INTRANET_CREATE", "INTRANET_EDIT", "INTRANET_DELETE", "INTRANET_PUBLISH",
    "BOOK_MEETING_VIEW", "BOOK_MEETING_CREATE", "BOOK_MEETING_EDIT", "BOOK_MEETING_DELETE", "BOOK_MEETING_APPROVE",
    "DOCUMENTS_VIEW", "DOCUMENTS_UPLOAD", "DOCUMENTS_EDIT", "DOCUMENTS_DELETE", "DOCUMENTS_SHARE", "DOCUMENTS_MANAGE_POOL",
    "PROJECTS_VIEW", "PROJECTS_CREATE", "PROJECTS_EDIT", "PROJECTS_DELETE", "PROJECTS_APPROVE", "PROJECTS_MANAGE_ALL",
    "USERS_VIEW", "USERS_CREATE", "USERS_EDIT", "USERS_DELETE", "USERS_MANAGE_ROLES", "USERS_MANAGE_PERMISSIONS", "USERS_AD_SYNC", "USERS_BULK_IMPORT",
    "USERS_BULK_ASSIGN_ROLE", "USERS_BULK_ENABLE", "USERS_BULK_DISABLE", "USERS_UNLOCK_ACCOUNT", "USERS_RESET_MFA", "USERS_EXPORT_SELECTED",
    "AUDIT_LOG_VIEW", "AUDIT_LOG_EXPORT", "AUDIT_LOG_MANAGE",
    "SETTINGS_VIEW", "SETTINGS_MANAGE", "SETTINGS_API_KEYS", "SETTINGS_BRANDING", "SETTINGS_NOTIFICATION", "SETTINGS_SSO",
    "ERP_VIEW", "ERP_MANAGE", "ERP_APPROVE", "ERP_REPORT",
    "E_OFFICE_VIEW", "E_OFFICE_CREATE", "E_OFFICE_APPROVE", "E_OFFICE_MANAGE",
    "DOCUMENT_MANAGEMENT_VIEW", "DOCUMENT_MANAGEMENT_UPLOAD", "DOCUMENT_MANAGEMENT_MANAGE", "DOCUMENT_MANAGEMENT_OCR",
    "ACADEMIC_VIEW", "ACADEMIC_MANAGE", "ACADEMIC_EXAM",
    "HR_VIEW", "HR_MANAGE", "HR_PAYROLL", "HR_ATTENDANCE",
  ],
  system_admin: [
    "DASHBOARD_VIEW", "DASHBOARD_MANAGE",
    "APPLICATION_HUB_VIEW", "APPLICATION_HUB_MANAGE", "APPLICATION_HUB_PIN",
    "INTRANET_VIEW", "INTRANET_CREATE", "INTRANET_EDIT", "INTRANET_DELETE", "INTRANET_PUBLISH",
    "BOOK_MEETING_VIEW", "BOOK_MEETING_CREATE", "BOOK_MEETING_EDIT", "BOOK_MEETING_DELETE", "BOOK_MEETING_APPROVE",
    "DOCUMENTS_VIEW", "DOCUMENTS_UPLOAD", "DOCUMENTS_EDIT", "DOCUMENTS_DELETE", "DOCUMENTS_SHARE", "DOCUMENTS_MANAGE_POOL",
    "PROJECTS_VIEW", "PROJECTS_CREATE", "PROJECTS_EDIT", "PROJECTS_DELETE", "PROJECTS_APPROVE", "PROJECTS_MANAGE_ALL",
    "USERS_VIEW", "USERS_CREATE", "USERS_EDIT", "USERS_DELETE", "USERS_MANAGE_ROLES", "USERS_MANAGE_PERMISSIONS", "USERS_AD_SYNC", "USERS_BULK_IMPORT",
    "USERS_BULK_ASSIGN_ROLE", "USERS_BULK_ENABLE", "USERS_BULK_DISABLE", "USERS_UNLOCK_ACCOUNT", "USERS_RESET_MFA", "USERS_EXPORT_SELECTED",
    "AUDIT_LOG_VIEW", "AUDIT_LOG_EXPORT", "AUDIT_LOG_MANAGE",
    "SETTINGS_VIEW", "SETTINGS_MANAGE", "SETTINGS_API_KEYS", "SETTINGS_BRANDING", "SETTINGS_NOTIFICATION", "SETTINGS_SSO",
    "ERP_VIEW", "ERP_MANAGE", "ERP_APPROVE", "ERP_REPORT",
    "E_OFFICE_VIEW", "E_OFFICE_CREATE", "E_OFFICE_APPROVE", "E_OFFICE_MANAGE",
    "DOCUMENT_MANAGEMENT_VIEW", "DOCUMENT_MANAGEMENT_UPLOAD", "DOCUMENT_MANAGEMENT_MANAGE", "DOCUMENT_MANAGEMENT_OCR",
    "ACADEMIC_VIEW", "ACADEMIC_MANAGE", "ACADEMIC_EXAM",
    "HR_VIEW", "HR_MANAGE", "HR_PAYROLL", "HR_ATTENDANCE",
  ],
  dean: [
    "DASHBOARD_VIEW", "DASHBOARD_MANAGE",
    "APPLICATION_HUB_VIEW", "APPLICATION_HUB_MANAGE", "APPLICATION_HUB_PIN",
    "INTRANET_VIEW", "INTRANET_CREATE", "INTRANET_EDIT", "INTRANET_PUBLISH",
    "BOOK_MEETING_VIEW", "BOOK_MEETING_CREATE", "BOOK_MEETING_APPROVE",
    "DOCUMENTS_VIEW", "DOCUMENTS_UPLOAD", "DOCUMENTS_EDIT",
    "PROJECTS_VIEW", "PROJECTS_APPROVE",
    "USERS_VIEW",
    "AUDIT_LOG_VIEW", "AUDIT_LOG_EXPORT",
    "ERP_VIEW", "ERP_MANAGE", "ERP_APPROVE", "ERP_REPORT",
    "E_OFFICE_VIEW", "E_OFFICE_CREATE", "E_OFFICE_APPROVE", "E_OFFICE_MANAGE",
    "DOCUMENT_MANAGEMENT_VIEW", "DOCUMENT_MANAGEMENT_UPLOAD", "DOCUMENT_MANAGEMENT_MANAGE", "DOCUMENT_MANAGEMENT_OCR",
    "ACADEMIC_VIEW", "ACADEMIC_MANAGE", "ACADEMIC_EXAM",
    "HR_VIEW", "HR_ATTENDANCE",
  ],
  dept_admin: [
    "DASHBOARD_VIEW", "DASHBOARD_MANAGE",
    "APPLICATION_HUB_VIEW", "APPLICATION_HUB_MANAGE", "APPLICATION_HUB_PIN",
    "INTRANET_VIEW", "INTRANET_CREATE", "INTRANET_EDIT", "INTRANET_DELETE", "INTRANET_PUBLISH",
    "BOOK_MEETING_VIEW", "BOOK_MEETING_CREATE", "BOOK_MEETING_EDIT", "BOOK_MEETING_DELETE", "BOOK_MEETING_APPROVE",
    "DOCUMENTS_VIEW", "DOCUMENTS_UPLOAD", "DOCUMENTS_EDIT", "DOCUMENTS_DELETE", "DOCUMENTS_SHARE", "DOCUMENTS_MANAGE_POOL",
    "PROJECTS_VIEW", "PROJECTS_CREATE", "PROJECTS_EDIT", "PROJECTS_DELETE", "PROJECTS_APPROVE",
    "USERS_VIEW", "USERS_CREATE", "USERS_EDIT",
    "USERS_BULK_ASSIGN_ROLE", "USERS_BULK_ENABLE", "USERS_BULK_DISABLE", "USERS_UNLOCK_ACCOUNT", "USERS_RESET_MFA",
    "AUDIT_LOG_VIEW", "AUDIT_LOG_EXPORT",
    "ERP_VIEW", "ERP_MANAGE",
    "E_OFFICE_VIEW", "E_OFFICE_CREATE", "E_OFFICE_APPROVE", "E_OFFICE_MANAGE",
    "DOCUMENT_MANAGEMENT_VIEW", "DOCUMENT_MANAGEMENT_UPLOAD", "DOCUMENT_MANAGEMENT_MANAGE",
    "ACADEMIC_VIEW", "ACADEMIC_MANAGE", "ACADEMIC_EXAM",
    "HR_VIEW", "HR_MANAGE", "HR_ATTENDANCE",
  ],
  user: [
    "DASHBOARD_VIEW", "DASHBOARD_MANAGE",
    "APPLICATION_HUB_VIEW", "APPLICATION_HUB_MANAGE", "APPLICATION_HUB_PIN",
    "INTRANET_VIEW", "INTRANET_CREATE", "INTRANET_EDIT", "INTRANET_DELETE",
    "BOOK_MEETING_VIEW", "BOOK_MEETING_CREATE", "BOOK_MEETING_DELETE",
    "DOCUMENTS_VIEW", "DOCUMENTS_UPLOAD", "DOCUMENTS_DELETE",
    "PROJECTS_VIEW", "PROJECTS_CREATE", "PROJECTS_EDIT",
    "ERP_VIEW",
    "E_OFFICE_VIEW", "E_OFFICE_CREATE",
    "DOCUMENT_MANAGEMENT_VIEW", "DOCUMENT_MANAGEMENT_UPLOAD",
    "ACADEMIC_VIEW",
    "HR_VIEW", "HR_PAYROLL", "HR_ATTENDANCE",
  ],
  viewer: [
    "DASHBOARD_VIEW",
    "APPLICATION_HUB_VIEW",
    "INTRANET_VIEW",
    "BOOK_MEETING_VIEW",
    "DOCUMENTS_VIEW",
    "PROJECTS_VIEW",
    "E_OFFICE_VIEW",
    "DOCUMENT_MANAGEMENT_VIEW",
    "ACADEMIC_VIEW",
  ],
};

export function hasPermission(roles: string[] | undefined, permission: PermissionCode): boolean {
  return (roles ?? []).some((role) => ROLE_PERMISSIONS[role as RoleCode]?.includes(permission));
}

export function isAdminOrHigher(roles: string[] | undefined): boolean {
  return (roles ?? []).some((role) => (ROLE_LEVELS[role as RoleCode] ?? 0) >= ROLE_LEVELS.system_admin);
}
