"use client";

import { useSession } from "next-auth/react";

export type RoleCode = "super_admin" | "system_admin" | "dean" | "dept_admin" | "user" | "viewer";

/**
 * Permission codes ตาม claude.md Permission Matrix
 */
export type PermissionCode =
  | "DASHBOARD_VIEW" | "DASHBOARD_MANAGE"
  | "APPLICATION_HUB_VIEW" | "APPLICATION_HUB_MANAGE" | "APPLICATION_HUB_PIN"
  | "INTRANET_VIEW" | "INTRANET_CREATE" | "INTRANET_EDIT" | "INTRANET_DELETE" | "INTRANET_PUBLISH"
  | "BOOK_MEETING_VIEW" | "BOOK_MEETING_CREATE" | "BOOK_MEETING_EDIT" | "BOOK_MEETING_DELETE" | "BOOK_MEETING_APPROVE"
  | "DOCUMENTS_VIEW" | "DOCUMENTS_UPLOAD" | "DOCUMENTS_EDIT" | "DOCUMENTS_DELETE" | "DOCUMENTS_SHARE" | "DOCUMENTS_MANAGE_POOL"
  | "PROJECTS_VIEW" | "PROJECTS_CREATE" | "PROJECTS_EDIT" | "PROJECTS_DELETE" | "PROJECTS_APPROVE" | "PROJECTS_MANAGE_ALL"
  | "USERS_VIEW" | "USERS_CREATE" | "USERS_EDIT" | "USERS_DELETE" | "USERS_MANAGE_ROLES" | "USERS_MANAGE_PERMISSIONS" | "USERS_AD_SYNC" | "USERS_BULK_IMPORT"
  | "AUDIT_LOG_VIEW" | "AUDIT_LOG_EXPORT" | "AUDIT_LOG_MANAGE"
  | "SETTINGS_VIEW" | "SETTINGS_MANAGE" | "SETTINGS_API_KEYS" | "SETTINGS_BRANDING" | "SETTINGS_NOTIFICATION" | "SETTINGS_SSO"
  | "ERP_VIEW" | "ERP_MANAGE" | "ERP_APPROVE" | "ERP_REPORT"
  | "E_OFFICE_VIEW" | "E_OFFICE_CREATE" | "E_OFFICE_APPROVE" | "E_OFFICE_MANAGE"
  | "DOCUMENT_MANAGEMENT_VIEW" | "DOCUMENT_MANAGEMENT_UPLOAD" | "DOCUMENT_MANAGEMENT_MANAGE" | "DOCUMENT_MANAGEMENT_OCR"
  | "ACADEMIC_VIEW" | "ACADEMIC_MANAGE" | "ACADEMIC_EXAM"
  | "HR_VIEW" | "HR_MANAGE" | "HR_PAYROLL" | "HR_ATTENDANCE"
  | "RESEARCH_VIEW" | "RESEARCH_MANAGE" | "RESEARCH_APPROVE"
  | "LEGAL_CLINIC_VIEW" | "LEGAL_CLINIC_MANAGE" | "LEGAL_CLINIC_APPROVE"
  | "SUPPORT_VIEW" | "SUPPORT_MANAGE";

/**
 * Role → Permission mapping ตาม claude.md Permission Matrix
 * Super Admin = all, others mapped explicitly.
 */
const ROLE_PERMISSIONS: Record<RoleCode, PermissionCode[]> = {
  super_admin: [], // all — handled separately
  system_admin: [
    "DASHBOARD_VIEW", "DASHBOARD_MANAGE",
    "APPLICATION_HUB_VIEW", "APPLICATION_HUB_MANAGE", "APPLICATION_HUB_PIN",
    "INTRANET_VIEW", "INTRANET_CREATE", "INTRANET_EDIT", "INTRANET_DELETE", "INTRANET_PUBLISH",
    "BOOK_MEETING_VIEW", "BOOK_MEETING_CREATE", "BOOK_MEETING_EDIT", "BOOK_MEETING_DELETE", "BOOK_MEETING_APPROVE",
    "DOCUMENTS_VIEW", "DOCUMENTS_UPLOAD", "DOCUMENTS_EDIT", "DOCUMENTS_DELETE", "DOCUMENTS_SHARE", "DOCUMENTS_MANAGE_POOL",
    "PROJECTS_VIEW", "PROJECTS_CREATE", "PROJECTS_EDIT", "PROJECTS_DELETE", "PROJECTS_APPROVE", "PROJECTS_MANAGE_ALL",
    "USERS_VIEW", "USERS_CREATE", "USERS_EDIT", "USERS_DELETE", "USERS_AD_SYNC", "USERS_BULK_IMPORT",
    "AUDIT_LOG_VIEW", "AUDIT_LOG_EXPORT",
    "SETTINGS_VIEW", "SETTINGS_MANAGE", "SETTINGS_BRANDING", "SETTINGS_NOTIFICATION",
    "ERP_VIEW", "ERP_MANAGE", "ERP_APPROVE", "ERP_REPORT",
    "E_OFFICE_VIEW", "E_OFFICE_CREATE", "E_OFFICE_APPROVE", "E_OFFICE_MANAGE",
    "DOCUMENT_MANAGEMENT_VIEW", "DOCUMENT_MANAGEMENT_UPLOAD", "DOCUMENT_MANAGEMENT_MANAGE", "DOCUMENT_MANAGEMENT_OCR",
    "ACADEMIC_VIEW", "ACADEMIC_MANAGE", "ACADEMIC_EXAM",
    "HR_VIEW", "HR_MANAGE", "HR_PAYROLL", "HR_ATTENDANCE",
    "RESEARCH_VIEW", "RESEARCH_MANAGE", "RESEARCH_APPROVE",
    "LEGAL_CLINIC_VIEW", "LEGAL_CLINIC_MANAGE", "LEGAL_CLINIC_APPROVE",
    "SUPPORT_VIEW", "SUPPORT_MANAGE",
  ],
  dean: [
    "DASHBOARD_VIEW",
    "APPLICATION_HUB_VIEW", "APPLICATION_HUB_PIN",
    "INTRANET_VIEW",
    "BOOK_MEETING_VIEW", "BOOK_MEETING_CREATE", "BOOK_MEETING_APPROVE",
    "DOCUMENTS_VIEW", "DOCUMENTS_UPLOAD", "DOCUMENTS_SHARE",
    "PROJECTS_VIEW", "PROJECTS_CREATE", "PROJECTS_APPROVE",
    "E_OFFICE_VIEW", "E_OFFICE_APPROVE",
    "ACADEMIC_VIEW",
    "HR_VIEW",
    "RESEARCH_VIEW", "RESEARCH_APPROVE",
    "LEGAL_CLINIC_VIEW",
    "SUPPORT_VIEW",
    "AUDIT_LOG_VIEW",
  ],
  dept_admin: [
    "DASHBOARD_VIEW",
    "APPLICATION_HUB_VIEW", "APPLICATION_HUB_PIN",
    "INTRANET_VIEW", "INTRANET_CREATE", "INTRANET_EDIT", "INTRANET_PUBLISH",
    "BOOK_MEETING_VIEW", "BOOK_MEETING_CREATE",
    "DOCUMENTS_VIEW", "DOCUMENTS_UPLOAD", "DOCUMENTS_EDIT", "DOCUMENTS_SHARE", "DOCUMENTS_MANAGE_POOL",
    "PROJECTS_VIEW", "PROJECTS_CREATE",
    "E_OFFICE_VIEW", "E_OFFICE_CREATE",
    "DOCUMENT_MANAGEMENT_VIEW", "DOCUMENT_MANAGEMENT_UPLOAD",
    "ACADEMIC_VIEW",
    "HR_VIEW",
    "RESEARCH_VIEW",
    "LEGAL_CLINIC_VIEW",
    "SUPPORT_VIEW",
  ],
  user: [
    "DASHBOARD_VIEW",
    "APPLICATION_HUB_VIEW", "APPLICATION_HUB_PIN",
    "INTRANET_VIEW",
    "BOOK_MEETING_VIEW", "BOOK_MEETING_CREATE", "BOOK_MEETING_EDIT",
    "DOCUMENTS_VIEW", "DOCUMENTS_UPLOAD", "DOCUMENTS_EDIT", "DOCUMENTS_SHARE",
    "PROJECTS_VIEW", "PROJECTS_CREATE", "PROJECTS_EDIT",
    "E_OFFICE_VIEW", "E_OFFICE_CREATE",
    "DOCUMENT_MANAGEMENT_VIEW", "DOCUMENT_MANAGEMENT_UPLOAD",
    "ACADEMIC_VIEW",
    "HR_VIEW",
    "RESEARCH_VIEW",
    "LEGAL_CLINIC_VIEW",
    "SUPPORT_VIEW",
  ],
  viewer: [
    "DASHBOARD_VIEW",
    "APPLICATION_HUB_VIEW",
    "INTRANET_VIEW",
    "BOOK_MEETING_VIEW",
    "DOCUMENTS_VIEW",
    "PROJECTS_VIEW",
    "E_OFFICE_VIEW",
    "ACADEMIC_VIEW",
    "HR_VIEW",
    "RESEARCH_VIEW",
    "LEGAL_CLINIC_VIEW",
    "SUPPORT_VIEW",
  ],
};

/**
 * Check if the current user's roles allow a specific permission.
 */
export function useHasPermission(permission: PermissionCode): boolean {
  const { data: session } = useSession();
  const roles = (session?.user as { roles?: string[] })?.roles ?? [];

  if (roles.includes("super_admin")) return true;

  return roles.some((role) => {
    const perms = ROLE_PERMISSIONS[role as RoleCode];
    return perms?.includes(permission);
  });
}

/**
 * Return list of user roles (sorted by level).
 */
export function useUserRoles(): RoleCode[] {
  const { data: session } = useSession();
  return ((session?.user as { roles?: string[] })?.roles ?? []) as RoleCode[];
}
